go_import_path: github.com/moisespsena-go/xbindata

language: go

go:
  # go vet --all doesn't work with 1.8 or 1.7
  - '1.9.x'
  - '1.10.x'
  - '1.11.x'
  - master

script:
  - make ci
  - make bench

sudo: false
